### ISSUE TITLE
"TypeError - can't dup NilClass" in `from-scratch` branch

### ISSUE THREAD

**Issue by chuck-wood** [zendesk/app_scaffold#90]
Environment:
* Windows 7
* Opera 53.0
* ruby 2.2.6p396 (2016-11-15 revision 56800) [x64-mingw32]
* npm 6.1.0
* zat 2.8.4
* node v9.3.0

Steps to reproduce (note that ZAT is already installed):
* open windows command prompt (`cmd`)
* `npm install --global webpack foreman karma-cli`
* `git clone https://github.com/zendesk/app_scaffold`
* `cd app_scaffold`
* `git checkout from-scratch`
* `npm install`
* `nf start`
* Navigate to https:_&lt;subdomain&gt;_.zendesk.com/agent/dashboard?zat=true

EXPECTED:
* No errors in console
* Scaffold loads in Zendesk interface

ACTUAL:
* No evidence of scaffold in Zendesk interface
* The following warning in console:
```
[WARN] No ENV file found
11:56:20 reload.1   |  One CLI for webpack must be installed. These are recommended choices, delivered as separate packages:
11:56:20 reload.1   |   - webpack-cli (https://github.com/webpack/webpack-cli)
11:56:20 reload.1   |     The original webpack full-featured CLI.
11:56:20 reload.1   |   - webpack-command (https://github.com/webpack-contrib/webpack-command)
11:56:20 reload.1   |     A lightweight, opinionated webpack CLI.
11:56:20 reload.1   |  We will use "yarn" to install the CLI via "yarn add -D".
11:56:20 reload.1   |  Which one do you like to install (webpack-cli/webpack-command):
11:56:22 server.1   |  == Sinatra (v1.4.8) has taken the stage on 4567 for development with backup from Thin
```
* The following stacktrace in console:
```
11:50:01 server.1   |  2018-06-19 11:50:01 - TypeError - can't dup NilClass:
11:50:01 server.1   |   d:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/zendesk_apps_support-4.7.0/lib/zendesk_apps_support/package.rb:256
:in `dup'
11:50:01 server.1   |   d:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/zendesk_apps_support-4.7.0/lib/zendesk_apps_support/package.rb:256
:in `runtime_translations'
11:50:01 server.1   |   d:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/zendesk_apps_support-4.7.0/lib/zendesk_apps_support/package.rb:132
:in `compile'
11:50:01 server.1   |   d:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/zendesk_apps_tools-2.8.4/lib/zendesk_apps_tools/server.rb:39:in `s
erve_installed_js'
11:50:01 server.1   |   d:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/zendesk_apps_tools-2.8.4/lib/zendesk_apps_tools/server.rb:14:in `b
lock in <class:Server>'
11:50:01 server.1   |   d:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1611:in `call'
11:50:01 server.1   |   d:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1611:in `block in compile!'
11:50:01 server.1   |   d:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:975:in `[]'
11:50:01 server.1   |   d:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:975:in `block (3 levels) in rout
e!'
11:50:01 server.1   |   d:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:994:in `route_eval'
11:50:01 server.1   |   d:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:975:in `block (2 levels) in rout
e!'
11:50:01 server.1   |   d:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1015:in `block in process_route'

11:50:01 server.1   |   d:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1013:in `catch'
11:50:01 server.1   |   d:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1013:in `process_route'
11:50:01 server.1   |   d:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:973:in `block in route!'
11:50:01 server.1   |   d:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:972:in `each'
11:50:01 server.1   |   d:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:972:in `route!'
11:50:01 server.1   |   d:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1085:in `block in dispatch!'
11:50:01 server.1   |   d:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `block in invoke'
11:50:01 server.1   |   d:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `catch'
11:50:01 server.1   |   d:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `invoke'
11:50:01 server.1   |   d:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1082:in `dispatch!'
11:50:01 server.1   |   d:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:907:in `block in call!'
11:50:01 server.1   |   d:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `block in invoke'
11:50:01 server.1   |   d:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `catch'
11:50:01 server.1   |   d:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `invoke'
11:50:01 server.1   |   d:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:907:in `call!'
11:50:01 server.1   |   d:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:895:in `call'
11:50:01 server.1   |   d:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rack-protection-1.5.5/lib/rack/protection/xss_header.rb:18:in `cal
l'
11:50:01 server.1   |   d:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rack-protection-1.5.5/lib/rack/protection/path_traversal.rb:16:in
`call'
11:50:01 server.1   |   d:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rack-protection-1.5.5/lib/rack/protection/json_csrf.rb:18:in `call
'
11:50:01 server.1   |   d:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rack-protection-1.5.5/lib/rack/protection/base.rb:49:in `call'
11:50:01 server.1   |   d:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rack-protection-1.5.5/lib/rack/protection/base.rb:49:in `call'
11:50:01 server.1   |   d:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rack-1.6.9/lib/rack/logger.rb:15:in `call'
11:50:01 server.1   |   d:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rack-1.6.9/lib/rack/commonlogger.rb:33:in `call'
11:50:01 server.1   |   d:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:219:in `call'
11:50:01 server.1   |   d:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:212:in `call'
11:50:01 server.1   |   d:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rack-1.6.9/lib/rack/head.rb:13:in `call'
11:50:01 server.1   |   d:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/sinatra-1.4.8/lib/sinatra/show_exceptions.rb:25:in `call'
11:50:01 server.1   |   d:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:182:in `call'
11:50:01 server.1   |   d:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:2013:in `call'
11:50:01 server.1   |   d:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1487:in `block in call'
11:50:01 server.1   |   d:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1787:in `synchronize'
11:50:01 server.1   |   d:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1487:in `call'
11:50:01 server.1   |   d:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/thin-1.7.2/lib/thin/connection.rb:86:in `block in pre_process'
11:50:01 server.1   |   d:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/thin-1.7.2/lib/thin/connection.rb:84:in `catch'
11:50:01 server.1   |   d:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/thin-1.7.2/lib/thin/connection.rb:84:in `pre_process'
11:50:01 server.1   |   d:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/thin-1.7.2/lib/thin/connection.rb:50:in `block in process'
11:50:01 server.1   |   d:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/eventmachine-1.2.5-x64-mingw32/lib/eventmachine.rb:1076:in `call'
11:50:01 server.1   |   d:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/eventmachine-1.2.5-x64-mingw32/lib/eventmachine.rb:1076:in `block
in spawn_threadpool'
```

Word wraps in stack trace are presumably due to Windows console :roll_eyes: 

NOTES

* Error does _not_ occur if `git checkout from-scratch` step is omitted.
* I attempted to resolve the warning about the webpack-cli by separately installing either one of the CLIs, but neither could be installed by webpack. No idea if that's related, but it doesn't halt the dev server from starting, which implies that it's not strictly necessary to fix.

**Comment by chuck-wood** [comment]
Ah, this is embarrassing. Just had to update ZAT. Updated to 2.9.4 and it seems to work fine now. Cheers.
